# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "libera"
description = "liberating libraries and utilities"
version = "0.0.3"
edition = "2021"
rust-version = "1.71.1" # sync with readme, check.sh & .github/workflows/check.yml
authors = ["José Luis Cruz <joseluis@andamira.net>"]
repository = "https://github.com/andamira/libera"
documentation = "https://docs.rs/libera"
license = "MIT OR Apache-2.0"
include = [
	"/src/**/*.rs",
	"/Cargo.toml",
	"/res/*",
	"/README.md",
	"/LICENSE-*",
]
categories = []
keywords = []
publish = true

[dependencies]

[features]
default = ["std"]
std = []

[dev-dependencies]

[badges]
# actively-developed, passively-maintained, looking-for-maintainer, as-is,
# experimental, deprecated, none
maintenance = { status = "experimental" }
